name: Deploy App to Server

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/rebuild:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to server using SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo docker stop rebuildcontainer
            sudo docker rm rebuildcontainer
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/rebuild:latest
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/rebuild:latest
            sudo docker run -d -p 8000:8000 \
            -e SERVERPORT=${{ secrets.SERVERPORT }} \
            -e DBUSER=${{ secrets.DBUSER }} \
            -e DBPASS=${{ secrets.DBPASS }} \
            -e DBHOST=${{ secrets.DBHOST }} \
            -e DBPORT=${{ secrets.DBPORT }} \
            -e DBNAME=${{ secrets.DBNAME }} \
            -e API_STORAGE=${{ secrets.API_STORAGE }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e EMAIL_HOST=${{ secrets.EMAIL_HOST }} \
            -e EMAIL_FROM=${{ secrets.EMAIL_FROM }} \
            -e EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} \
            -e EMAIL_PORT=${{ secrets.EMAIL_PORT }} \
            -e RDB_ADDR=${{ secrets.RDB_ADDR }} \
            -e RDB_USER=${{ secrets.RDB_USER }} \
            -e RDB_PASS=${{ secrets.RDB_PASS }} \
            -e OPEN_AI_KEY=${{ secrets.OPEN_AI_KEY }} --name rebuildcontainer ${{ secrets.DOCKERHUB_USERNAME }}/rebuild:latest 
            

  