name: Deploy App to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to server using SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export PATH=$PATH:/usr/local/go/bin
            cd juang/Rebuild-API
            git pull origin main
            go build -o rebuild main.go
            ./rebuild
            
      - name: Exit the workflow (success)
        run: exit 0 